package myFirstOne;

public class ExceptionTest {

	public static void main(String[] args) {
		int [] array = {1,5,8};
        try{
        	int a;
        	for (a = 0;a < 4;a++) {
        		System.out.println(array[a]);
        	}
        {  
       /* catch (Exception e) {
        	System.out.println(e.getMessage());
        	
        }
        finally {
        	System.out.println("");*/
        }
	}


